apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: modeldynamics
  name: lll
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: This is a Model Dynamics Helix project.
  destinations:
  - namespace: helix-lll
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
